In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [4]:
a.shape

(4,)

## Array Arithmetic / Vectorization

__Arithmetic operations behave differently based on the type of the _other_ operand. For example.__

If the other operand is a scalar (_single value types_ like `int`, `float`, `boolean`, `string`, etc.), then the operation is performed on every element using the same scalar as the second operand:

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr * 10)

[[10 20 30]
 [40 50 60]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
arr + np.array([1, 2, 3])

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
np.array([1, 2, 3]).shape

(3,)

In [14]:
arr = np.array([1, 2, 3])
arr.shape??

Type:        tuple
String form: (3,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.


In [18]:
np.ones((10, 5 ))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.arange(4, 12, 2)

array([ 4,  6,  8, 10])

In [36]:
np.random.randn(2, 3)

array([[-0.41478999, -0.87304136, -0.23290474],
       [ 0.30277282,  0.44985592,  1.06013982]])

In [37]:
np.array('abc')

array('abc', dtype='<U3')

In [38]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [39]:
np.array([[1, 1], [2, 2]])

array([[1, 1],
       [2, 2]])

In [40]:
np.array(((1, 1), (2, 2)))

array([[1, 1],
       [2, 2]])

In [41]:
res = np.array(((1, 1), (2, 2)))

In [42]:
res.dtype

dtype('int64')

In [43]:
arr = np.array([[[1, 1], [2, 2], [3, 3]], 
                [[4, 4], [5, 5], [6, 6]],
                [[7, 7], [8, 8], [9, 9]]])

In [44]:
arr.ndim

3

In [45]:
arr.shape

(3, 3, 2)

In [46]:
arr.dtype

dtype('int64')

In [48]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:

np.ones((2, 3)).astype('int64')

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
np.ones((2, 3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [51]:
np.ones((2, 3)) + np.array([[1, 2, 3], [4, 5, 6]])

array([[2., 3., 4.],
       [5., 6., 7.]])

In [52]:
np.ones((3, 3)) + np.array([[8], [9]])

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [53]:
np.ones((2, 3, 2)) + np.array([[[1, 2]], [[3, 4]]])

array([[[2., 3.],
        [2., 3.],
        [2., 3.]],

       [[4., 5.],
        [4., 5.],
        [4., 5.]]])

In [57]:
a1 = np.ones((3, 3)); a2 = np.array([1, 2, 3])

In [58]:
a1 + a2

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [59]:
a1 = np.ones((2, 3, 2)) + np.array([[[8, 9]], [[88, 99]]])


In [60]:
a1

array([[[  9.,  10.],
        [  9.,  10.],
        [  9.,  10.]],

       [[ 89., 100.],
        [ 89., 100.],
        [ 89., 100.]]])

In [61]:
np.ones((2, 3, 2)) + np.array([[[8, 9],     [8, 9],   [8, 9]], 
                               [[88, 99], [88, 99], [88, 99]]])

array([[[  9.,  10.],
        [  9.,  10.],
        [  9.,  10.]],

       [[ 89., 100.],
        [ 89., 100.],
        [ 89., 100.]]])

In [62]:
np.array([[10, 11, 12], [13, 14, 15]])

array([[10, 11, 12],
       [13, 14, 15]])

In [63]:
a =  np.array([[10, 11, 12], [13, 14, 15]])
a[0]

array([10, 11, 12])

In [64]:
a[0][0]

10

In [65]:
a[0][-1]

12

In [66]:
a[0, -1]

12

In [67]:
a[(0, -1)]

12

In [82]:
a = np.array([[[1, 2], [3, 4]], [[4, 6], [5, 8]]])

In [83]:
a

array([[[1, 2],
        [3, 4]],

       [[4, 6],
        [5, 8]]])

In [84]:
a[1]

array([[4, 6],
       [5, 8]])

In [85]:
a[1, 0]

array([4, 6])

In [86]:
a

array([[[1, 2],
        [3, 4]],

       [[4, 6],
        [5, 8]]])

In [87]:
a[0][0][0] = 100 

In [88]:
a

array([[[100,   2],
        [  3,   4]],

       [[  4,   6],
        [  5,   8]]])

In [89]:
a[0][0] = 100

In [90]:
a

array([[[100, 100],
        [  3,   4]],

       [[  4,   6],
        [  5,   8]]])

In [91]:
a[0][0] = [99, 100]

In [93]:
a

array([[[ 99, 100],
        [  3,   4]],

       [[  4,   6],
        [  5,   8]]])

In [94]:
a[0] = [1000, 1000]

In [95]:
a

array([[[1000, 1000],
        [1000, 1000]],

       [[   4,    6],
        [   5,    8]]])

In [102]:
a = np.ones((2, 3))

In [103]:
last_row = a[-1]

In [105]:
last_row[-1] = 456

In [106]:
a

array([[  1.,   1.,   1.],
       [  1.,   1., 456.]])

In [107]:
np.ones(5)[:2]

array([1., 1.])

In [108]:
a = np.arange(9)

In [110]:
a.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
a.shape = (3, 3)

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
a = np.arange(36).reshape((4, 3, 3))


In [118]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [121]:
a[1:3,:2,1:]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

In [122]:
a[1:3,:2,1:] = 0

In [123]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9,  0,  0],
        [12,  0,  0],
        [15, 16, 17]],

       [[18,  0,  0],
        [21,  0,  0],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [124]:
a = np.arange(9).reshape((3, 3))

In [125]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
a[:2, :2]

array([[0, 1],
       [3, 4]])

In [128]:
a[:, -1]

array([2, 5, 8])

In [129]:
a[:, 2:]

array([[2],
       [5],
       [8]])

In [130]:
a[1, 1:]

array([4, 5])

In [131]:
a[1:,:]

array([[3, 4, 5],
       [6, 7, 8]])

In [150]:
a = np.arange(15).reshape(5, 3)

In [151]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [153]:
a[[False, True, False, True, False]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [140]:
a

array([[2., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [165]:
a = np.arange(24).reshape((3, 4, 2))

In [166]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [167]:
a[:2, [False, True, False, True], -1]

array([[ 3,  7],
       [11, 15]])

In [168]:
a[:2, [False, True, False, True], 1:]

array([[[ 3],
        [ 7]],

       [[11],
        [15]]])

In [169]:
a = np.arange(9).reshape(3, 3)

In [170]:
a[[2, 1]]

array([[6, 7, 8],
       [3, 4, 5]])

In [171]:
a[[0, 1, 2], [2, 1, 0]]

array([2, 4, 6])

In [172]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [173]:
a = np.array([[0], [1], [2], [3]]) 
a[[-1, -1, 0]]


array([[3],
       [3],
       [0]])

In [174]:
a = np.arange(9).reshape((3, 3))

In [175]:
a = np.arange(4)

In [176]:
a

array([0, 1, 2, 3])

In [177]:
a.T

array([0, 1, 2, 3])

In [184]:
a = np.arange(12).reshape((3, 4))

In [185]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [190]:
m1 = np.arange(6).reshape(2, 3)
m2 = np.arange(6, 12).reshape(3, 2)
print(m1, m2, sep='\n')
m1.dot(m2)


[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


array([[ 28,  31],
       [100, 112]])

In [191]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
numpy.sqrt(a)

NameError: name 'numpy' is not defined

In [193]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [194]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [195]:
a.floor_divide(a)

AttributeError: 'numpy.ndarray' object has no attribute 'floor_divide'

In [196]:
np.floor_divide(a, a)

/Users/jversoza/.virtualenvs/data/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [197]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
a = np.arange(9).reshape(3, 3)

In [199]:
a.mean()

4.0

In [202]:
a.mean(axis=0)

array([3., 4., 5.])

In [204]:
a = np.arange(9).reshape(3, 3)
np.where(a < 5, 'YAS', 'OH NO')


array([['YAS', 'YAS', 'YAS'],
       ['YAS', 'YAS', 'OH NO'],
       ['OH NO', 'OH NO', 'OH NO']], dtype='<U5')

In [205]:
a = np.array([[1, 1, 2], [2, 1, 1], [3, 1, 3]])

In [206]:
a

array([[1, 1, 2],
       [2, 1, 1],
       [3, 1, 3]])

In [207]:
a.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [208]:
np.unique(a)

array([1, 2, 3])

In [209]:
a.sort()

In [210]:
a

array([[1, 1, 2],
       [1, 1, 2],
       [1, 3, 3]])