In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [4]:
a.shape

(4,)

## Array Arithmetic / Vectorization

__Arithmetic operations behave differently based on the type of the _other_ operand. For example.__

If the other operand is a scalar (_single value types_ like `int`, `float`, `boolean`, `string`, etc.), then the operation is performed on every element using the same scalar as the second operand:

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr * 10)

[[10 20 30]
 [40 50 60]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
arr + np.array([1, 2, 3])

array([[2, 4, 6],
       [5, 7, 9]])