In [1]:
import numpy as np

In [2]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr = np.arange(0, 3)

print(arr) # [0 1 2]
print(arr.dtype) # int64

float_arr = arr.astype('float64')

print(float_arr) # [0. 1. 2.] (floating point numbers, 64 bits)
print(float_arr.dtype) #

[0 1 2]
int64
[0. 1. 2.]
float64


In [12]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[1, 1, 1], [10, 10, 10]])
print(data1 + data2)

[[ 2  3  4]
 [14 15 16]]


In [14]:
data = np.arange(1, 4)
print(data * 100)

[100 200 300]


In [16]:
data1 = np.array([[1, 2], [3, 4]])
data2 = np.array([[2, 2], [2, 2]])
data1 > data2

array([[False, False],
       [ True,  True]])

In [22]:
data = np.zeros(10)
sub = data[5:]
sub[0] = 99

In [24]:
data

array([ 0.,  0.,  0.,  0.,  0., 99.,  0.,  0.,  0.,  0.])

In [26]:
arr = np.array([1, 2, 3])
#twin_arr = arr.copy()
twin_arr = arr
twin_arr[0] = 99
print(arr, twin_arr)

[99  2  3] [99  2  3]


In [28]:
animals = np.array([['ant', 'bat', 'cat'], ['dog', 'elk', 'fox'], ['gnu', 'hen', 'ibis']])

In [29]:
animals

array([['ant', 'bat', 'cat'],
       ['dog', 'elk', 'fox'],
       ['gnu', 'hen', 'ibis']], dtype='<U4')

In [30]:
animals[2][1]

'hen'

In [31]:
animals[2, 1]

'hen'

In [32]:
nested = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]])

In [33]:
nested

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
nested[0] = 480

In [35]:
nested

array([[[480, 480],
        [480, 480]],

       [[  5,   6],
        [  7,   8]]])

In [36]:
animals[:2, :2]

array([['ant', 'bat'],
       ['dog', 'elk']], dtype='<U4')

In [37]:
animals[1:2,1:]

array([['elk', 'fox']], dtype='<U4')

In [38]:
animals[:, 2:]

array([['cat'],
       ['fox'],
       ['ibis']], dtype='<U4')

In [40]:
max([x for x in range(4)])

3